# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IEhO0UveN73Urrotuf6A8aV-gwAc_Zf
"""

# SECTION A

#1 Create a function that takes three integer arguments (a, b, c) and returns the amount of integers which are of equal value.

def num(x,y,z,) :
  if x == y and x == z:
    return 3
  elif x==y or x==z:
    return 2
  else:
    return 0
print(num(2,1,3))

#2 Write a function that converts a dictionary into a list of keys-values tuples.
dict = { 'aman': 1, 'achintya': 2, 'atharva': 3 }
list = [(a, b) for a, b in dict.items()]
print(sorted(list))

#3 Write a function that creates a dictionary with each (key, value) pair being the (lower case, upper case) versions of a letter, respectively.
list = ['a','e','i','o','u']
a = {}

for letters in list:
  b = letters.upper()
  a.update({letters:b})
print(a)

#4 Write a function, that replaces all vowels in a string with a specified vowel.
print("Enter the String: ")
str = input()

print("Enter a character: ")
char = input()

newstr = ""
for i in range(len(str)):
    if str[i]=='a' or str[i]=='e' or str[i]=='i' or str[i]=='o' or str[i]=='u':
        newstr = newstr + char
    else:
        newstr = newstr + str[i]

print("\nOriginal String:", str)
print("New String:", newstr)

# SECTION B

def my_function():
  print("Hello from a function")

my_function()

def my_function(country = "india"):
  print("I am from " + country)

my_function("potugal")
my_function("argentina")
my_function()
my_function("Brazil")

def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "mango"]

my_function(fruits)

def convertTemp(c):
   f = (c * 1.8) + 32
   return f
    

cel = float(input('Enter temperature in Celsius: '))


fahr = convertTemp(cel)
print('%0.1f degrees Celsius is equivalent to %0.1f degrees Fahrenheit' %(cel, fahr))

def kilometre_1(km):  
    conversion_ratio_1= 0.621371  
    miles_1 = km * conversion_ratio_1  
    print ("The speed value of car in Miles: ", miles_1)  
km = float (input ("Please enter the speed of car in Kilometre as a unit: "))  
kilometre_1(km)